# -*- coding: utf-8 -*-
"""Comparação - contraste.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvqEpwTR00t83L7WO0XWnrs9_1_5hJde
"""

# Bibliotecas:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import sympy as sp
from scipy.integrate import cumtrapz
from gapp import gp
plt.rcParams['text.usetex'] = True

# constantes
#H0 = 67.4
#O_m0 = 0.315
O_L0 = 0.7
#w1 = -1.028
#w0 = -0.957
#wa = -0.29
O_k0 = -0.056
c = 1



# SOMBREADA

# baixando os dados de f

data_fz = np.genfromtxt('/home/usuario/Documentos/Dados/fz_data.csv', delimiter=', ')

z_gapp = data_fz[:,0]
fz = data_fz[:,1]
sig_fz = data_fz[:,2]


# nomeando
x_gapp = z_gapp
y_gapp = fz
e = sig_fz

# xmin, xmax and nstar are interpreted as two-dimensional vectors
xmin = 0
xmax = 5.0
nstar = 1000

# initial values of the hyperparameters of the squared-exponential covariance function
initheta = [2.0, 2.0]

# initialization of the Gaussian Process
g = gp.GaussianProcess(x_gapp, y_gapp, e, cXstar=(xmin, xmax, nstar))

# training of the hyperparameters and reconstruction of the function
(rec, theta) = g.gp(theta=initheta)

xi = rec[:, 0]

y_pred = rec[:, 1]
sigma  = rec[:, 2]

y_pred_95_less = y_pred - 1.9600*sigma
y_pred_95_plus = y_pred + 1.9600*sigma




#### definindo o fator de escala

a = 1/(1+xi)

x1 = cumtrapz(y_pred, x = np.log(a), initial = 0.001)

delta_rec = np.exp(x1)

sig_d = np.sqrt( (delta_rec**2)*(sigma**2) )

#####################################################################################



# Modelo LCDM:
def Densidade(t, y):    # t é o fator de escala e y é o delta (contraste)
    D_RG  = y[0]     # contraste
    dD_RG = y[1]    # primeira derivada do contraste
    
    H0 = 67.2
    O_m0 = 0.339

    O_m = O_m0*t**(-3)
    O_L = 1 - O_m0

    H_RG = H0*np.sqrt(O_m + O_L)    # H(z)
    dH_RG = - (H_RG/t) - 0.5*(H0/t)*(H0/H_RG)*(O_m - 2*O_L)        # derivada do H(z)

# funções definidas somente para facilitar a escrita da derivada segunda do contraste
    faux1 = 3*H0**2
    faux2 = 2*(t**2)*(H_RG**2)

    ddD_RG = - ((3/t) + (dH_RG/H_RG))*dD_RG + (faux1/faux2)*O_m*D_RG   #  eq. da derivada segunda do contraste
    return [dD_RG, ddD_RG]


# Espaço de integração:
t_span = [0.17, 1]   # intervalo de integração do fator de escala
t = np.linspace(0.17, 1, 1000)

# Condições iniciais:
y0 = [0.17, 1]


# Solução:
sol = solve_ivp(Densidade, t_span, y0, t_eval=t, method='LSODA') # função que quero resolver, o intervalo de integração, as condições iniciais, o linspace e o método
D_RG = sol.y[0]
dD_RG = sol.y[1]


# definindo o redshift
z = 1/sol.t - 1



# plotando o contraste x z
#plt.plot(z, D_RG, color='blue', linewidth = 2, label='$\Lambda$CDM')
#plt.legend()
#plt.xlabel('z')
#plt.ylabel('$\delta$')
#plt.savefig('delta(z).png', dpi=520, format='png', bbox_inches='tight')
#plt.show()



###############################################################################

# Modelo w0waCDM:
def Densidade_w(t, y):    # t é o fator de escala e y é o delta (contraste)
    D_RG_w  = y[0]     # contraste
    dD_RG_w = y[1]    # primeira derivada do contraste
    
    H0 = 67.4
    O_m0 = 0.320
    w0 = -0.876
    wa = -0.07

    O_m = O_m0*t**(-3)
    O_L = O_L0*np.exp(-3*wa*(1-t))*(t**(-3*(1 + w0 + wa) ) )

    H_RG_w = H0*np.sqrt(O_m + O_L)    # H(z)
    dH_RG_w = - (H_RG_w/t) - 0.5*(H0/t)*(H0/H_RG_w)*(O_m - 2*O_L)        # derivada do H(z)

# funções definidas somente para facilitar a escrita da derivada segunda do contraste
    faux1 = 3*H0**2
    faux2 = 2*(t**2)*(H_RG_w**2)

    ddD_RG_w = - ((3/t) + (dH_RG_w/H_RG_w))*dD_RG_w + (faux1/faux2)*O_m*D_RG_w   #  eq. da derivada segunda do contraste
    return [dD_RG_w, ddD_RG_w]


# Espaço de integração:
t_span = [0.17, 1]   # intervalo de integração do fator de escala
t = np.linspace(0.17, 1, 1000)

# Condições iniciais:
y0 = [0.17, 1]


# Solução:
sol_w = solve_ivp(Densidade_w, t_span, y0, t_eval=t, method='LSODA') # função que quero resolver, o intervalo de integração, as condições iniciais, o linspace e o método
D_RG_w = sol_w.y[0]
dD_RG_w = sol_w.y[1]


# definindo o redshift
z = 1/sol_w.t - 1

# Modelo AB-f(R):

# Condições iniciais
ti = 0.17
O_r0 = 0
mu = 10**(-7)
k = 0.125


###################################################################################

def Den_AB(t, y, H0, O_m0, b):
    H_AB   = y[0]
    dH_AB  = y[1]
    ddH_AB = y[2]
    D_AB   = y[3]
    dD_AB  = y[4]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)

    R_vac = 12*H0**2
    e_AB = R_vac/np.log(1 + np.exp(2*b))
    M2 = e_AB/mu

    R_AB = 6*H_AB*(2*H_AB + t*dH_AB)
    alpha = (R_AB/e_AB) - b

    if abs(alpha) < 25:
      s = 1/np.cosh(alpha)
    else:
      s = 0

    A = (H0**2)*(3*O_m + 4*O_r)
    B = (2*t*H_AB*dH_AB*R_AB)/(3*M2)
    C = t*H_AB*dH_AB*(np.tanh(alpha) + 1)

    c1 = 6*(t**2)*(H_AB**2)/e_AB
    c2 = ddH_AB + ((dH_AB**2)/H_AB) + (5*dH_AB/t)

    if abs(alpha) < 15:
      D = ((c1*c2*s)**2)*np.tanh(alpha)
    else:
      D = 0

    if abs(alpha) < 15:
      E = 6*(t**3)*(H_AB**3)*((1/(3*M2)) + (0.5*s*s/e_AB))
    else:
      E = 6*(t**3)*(H_AB**3)*(1/(3*M2))
    F = (11*dH_AB**2/(t*H_AB)) + (dH_AB**3/(H_AB**2)) + (6*ddH_AB/t) + (4*dH_AB*ddH_AB/H_AB)
    dddH_AB = - ((A + B + C - D)/E) - F

    fR = 0.5*(1 + np.tanh(alpha)) + R_AB/(3*M2)
    fRR= (0.5/e_AB)*s**2 + 1/(3*M2)

    R_0 = R_vac
    alpha_0 = (R_0/e_AB) - b

    fR_0 = 0.5*(1 + np.tanh(alpha_0)) + (R_0/(3*M2))
    fRR_0 = (0.5/e_AB)*((1/np.cosh(alpha_0))**2) + (1/3*M2)

    gaux3 = 9e6*(k*k/(t*t))*(fRR/fR)*(fR_0/fRR_0)
    #gaux3 = (fRR/fR)*(k/t)**2
    Geffn = (1/(fR))*(1 + 4*(c**2)*gaux3)/(1 + 3*(c**2)*gaux3)

    fAB1 = 3*Geffn*H0**2
    fAB2 = 2*t*t*H_AB*H_AB

    ddD_AB = - ((3/t) + (dH_AB/H_AB))*dD_AB + (fAB1/fAB2)*O_m*D_AB
    return [dH_AB, ddH_AB, dddH_AB, dD_AB, ddD_AB]

def sol_DAB(H0, O_m0, b):
    #Integração:
    t_span = [ti, 1]
    t = np.linspace(ti, 1, 1000)

    # Condições iniciais:
    O_mi = O_m0*ti**(-3)
    O_ri = O_r0*ti**(-4)
    O_L = 1 - O_m0
    Hi = H0*np.sqrt(O_mi + O_ri + O_L)
    dHi = - ((H0**2)/(2*ti*Hi))*(3*O_mi + 4*O_ri)
    ddHi = 0.5*(H0/(ti*Hi))**2*(Hi + ti*dHi)*(3*O_mi + 4*O_ri) + 0.5*(H0/(ti*Hi))**2*Hi*(9*O_mi + 16*O_ri)
    y0 = [Hi, dHi, ddHi, ti, 1]

    # Solução:
    sol = solve_ivp(Den_AB, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, b))
    D_AB  = sol.y[3]
    return D_AB

#print(Sol_DAB(70, 0.3, 2))


####################################################################################

# Modelo wCDM:
def Densidade_w1(t, y):    # t é o fator de escala e y é o delta (contraste)
    D_RG_w1  = y[0]     # contraste
    dD_RG_w1 = y[1]    # primeira derivada do contraste
    
    H0 = 67.3
    O_m0 = 0.306
    w0 = -0.887

    O_m = O_m0*t**(-3)
    O_L = O_L0*(t**(-3*(1+w0) ) )

    H_RG_w1 = H0*np.sqrt(O_m + O_L)    # H(z)
    dH_RG_w1 = - (H_RG_w1/t) - 0.5*(H0/t)*(H0/H_RG_w1)*(O_m - 2*O_L)        # derivada do H(z)

# funções definidas somente para facilitar a escrita da derivada segunda do contraste
    faux1 = 3*H0**2
    faux2 = 2*(t**2)*(H_RG_w1**2)

    ddD_RG_w1 = - ((3/t) + (dH_RG_w1/H_RG_w1))*dD_RG_w1 + (faux1/faux2)*O_m*D_RG_w1   #  eq. da derivada segunda do contraste
    return [dD_RG_w1, ddD_RG_w1]


# Espaço de integração:
t_span = [0.17, 1]   # intervalo de integração do fator de escala
t = np.linspace(0.17, 1, 1000)

# Condições iniciais:
y0 = [0.17, 1]


# Solução:
sol_w1 = solve_ivp(Densidade_w1, t_span, y0, t_eval=t, method='LSODA') # função que quero resolver, o intervalo de integração, as condições iniciais, o linspace e o método
D_RG_w1 = sol_w1.y[0]
dD_RG_w1 = sol_w1.y[1]


# definindo o redshift
z = 1/sol_w1.t - 1


################################################################################

# O_KCDM model:
def contrast_OKCDM(t, y, O_m0, O_K0):
  D_OK = y[0]
  dD_OK = y[1]
  O_K = O_K0*t**(-2)
  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)
  O_L = 1 - O_m0 - O_r0
  E_OK = np.sqrt(O_K + O_m + O_r + O_L)
  dE_OK = - (E_OK/t) - (0.5/t)*(1/E_OK)*(O_m + 2*O_r - 2*O_L)
  ddD_OK = - ((3/t) + (dE_OK/E_OK))*dD_OK + (3/(2*t**2*E_OK**2))*O_m*D_OK
  return [dD_OK, ddD_OK]

def D_OKCDM(O_m0, O_K0):
  y0 = [0.17, 1]
  sol_OK = solve_ivp(contrast_OKCDM, t_span, y0, t_eval=t, method='LSODA', args=(O_m0, O_K0))
  D_OK = sol_OK.y[0]
  return D_OK




##########################################################################################

p = 0.17 #0.049787068
t = np.linspace(p, 1, 1000)
z = (1/t) - 1



# Modelo Starobinski n=1
def contrast_S_n1(t, y, H0, O_m0, mu):
    yH = y[0]
    YH = y[1]
    D_S = y[2]
    dD_S = y[3]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)
    chi = O_r0/O_m0
    ms = (H0**2)*O_m0
    R = 3*ms*(4*yH + t*YH + t**(-3))

    Lbd = 3 * H0**2 * (1 - O_m0)
    Rs = 2*Lbd*mu
    star = 1 + (R/Rs)**2

    lmu2 = Lbd * mu**2

    f = R - 2*Lbd*(1 - (star**(-1)))
    fR = 1 - (R/lmu2)*(star**(-2))
    fRR = (1/lmu2)*(4 * (R/Rs)**2 * star**(-1) - 1) * star**(-2)

    yaux1 = yH + t**(-3) + chi*t**(-4)
    yaux2 = t**(-3) + 2*chi*t**(-4)
    j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
    j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
    j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
    J1 = (1/t)*(1 + j1)
    J2 = (1/t)*(j2/t)
    J3 = (1/t)*(j3/t)
    dYH = - J1*YH - J2*yH - J3

    H = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
    dH = (R/(6*t*H)) - (2*H/t)

    gaux3 = (fRR/fR)*(k*(H0/100)/t)**2
    Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
    faux1 = 3*Geffn*H0**2
    faux2 = 2*t*t*H*H

    ddD_S = - ((3/t) + (dH/H))*dD_S + (faux1/faux2)*O_m*D_S
    return [YH, dYH, dD_S, ddD_S]

def D_S_n1(H0, O_m0, mu):
    y0 = [(1-O_m0)/O_m0, 0, 0.17, 1]
    sol_S = solve_ivp(contrast_S_n1, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-10), args=(H0, O_m0, mu))
    D1_S = sol_S.y[2]
    return D1_S

#print(solD_HS(70,0.3,1,1)[999])



####################################################################################

# Modelo Starobinski n=2
def contrast_S_n2(t, y, H0, O_m0, mu):
    yH = y[0]
    YH = y[1]
    D_S = y[2]
    dD_S = y[3]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)
    chi = O_r0/O_m0
    ms = (H0**2)*O_m0
    R = 3*ms*(4*yH + t*YH + t**(-3))

    Lbd = 3 * H0**2 * (1 - O_m0)
    Rs = 2*Lbd*mu
    star = 1 + (R/(2*Lbd*mu))**2
    
    Delta = 10**(-7)

    M2 = Rs/Delta

    lmu2 = Lbd * (mu**2)
    star2 = (2*Lbd*mu)**2 + R**2

    f = R - 2*Lbd*(1 - (star**(-2))) + ((R**2)/(6*M2))
    fR = 1 - (2*R/lmu2)*(star**(-3)) + (R/(3*M2))
    fRR = ((2**7)*(Lbd**5)*(mu**4)/(star2**3))*(6*((R**2)/star2)- 1) + (1/(3*M2))

    yaux1 = yH + t**(-3) + chi*t**(-4)
    yaux2 = t**(-3) + 2*chi*t**(-4)
    j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
    j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
    j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
    J1 = (1/t)*(1 + j1)
    J2 = (1/t)*(j2/t)
    J3 = (1/t)*(j3/t)
    dYH = - J1*YH - J2*yH - J3

    H = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
    dH = (R/(6*t*H)) - (2*H/t)

    gaux3 = (fRR/fR)*(k*(H0/100)/t)**2
    Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
    faux1 = 3*Geffn*H0**2
    faux2 = 2*t*t*H*H

    ddD_S = - ((3/t) + (dH/H))*dD_S + (faux1/faux2)*O_m*D_S
    return [YH, dYH, dD_S, ddD_S]

def D_S_n2(H0, O_m0, mu):
    y0 = [(1-O_m0)/O_m0, 0, 0.17, 1]
    sol_S = solve_ivp(contrast_S_n2, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-10), args=(H0, O_m0, mu))
    D1_S = sol_S.y[2]
    return D1_S


#######################################################################################

# Modelo Hu-Sawicki n=1
def contrast_HS_n1(t, y, H0, O_m0, mu):
    yH = y[0]
    YH = y[1]
    D_HS = y[2]
    dD_HS = y[3]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)
    chi = O_r0/O_m0
    ms = (H0**2)*O_m0
    R = 3*ms*(4*yH + t*YH + t**(-3))

    Lbd = 3*(H0**2)*(1 - O_m0)

    chi = O_r0/O_m0
    ms = (H0**2)*O_m0

    R = 3*ms*(4*yH + t*YH + t**(-3))
    
    n=1

    A = (R**n) + (mu**(2*n))
    B = (R**n)
    C = (n+1)*(R**(2*n - 2)) - (n- 1)*(mu**(2*n))*(R**(n-2))
    D = A**3

    f = R - 2*Lbd*(B/A)
    fR = 1 - 2*n*Lbd*(mu**(2*n))*(B/A)*(1/(R*A))
    fRR = 2*n*Lbd*(mu**(2*n))*(C/D)

    yaux1 = yH + t**(-3) + chi*t**(-4)
    yaux2 = t**(-3) + 2*chi*t**(-4)
    j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
    j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
    j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
    J1 = (1/t)*(1 + j1)
    J2 = (1/t)*(j2/t)
    J3 = (1/t)*(j3/t)
    dYH = - J1*YH - J2*yH - J3

    H = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
    dH = (R/(6*t*H)) - (2*H/t)

    gaux3 = (fRR/fR)*(k*(H0/100)/t)**2
    Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
    faux1 = 3*Geffn*H0**2
    faux2 = 2*t*t*H*H

    ddD_HS = - ((3/t) + (dH/H))*dD_HS + (faux1/faux2)*O_m*D_HS
    return [YH, dYH, dD_HS, ddD_HS]

def D_HS_n1(H0, O_m0, mu):
    y0 = [(1-O_m0)/O_m0, 0, 0.17, 1]
    sol_S = solve_ivp(contrast_HS_n1, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, mu))
    D1_S = sol_S.y[2]
    return D1_S


################################################################################


# Modelo Hu-Sawicki n=2
def contrast_HS_n2(t, y, H0, O_m0, mu):
    yH = y[0]
    YH = y[1]
    D_HS = y[2]
    dD_HS = y[3]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)
    chi = O_r0/O_m0
    ms = (H0**2)*O_m0
    R = 3*ms*(4*yH + t*YH + t**(-3))

    Lbd = 3*(H0**2)*(1 - O_m0)

    chi = O_r0/O_m0
    ms = (H0**2)*O_m0

    R = 3*ms*(4*yH + t*YH + t**(-3))
    
    n=2

    A = (R**n) + (mu**(2*n))
    B = (R**n)
    C = (n+1)*(R**(2*n - 2)) - (n- 1)*(mu**(2*n))*(R**(n-2))
    D = A**3

    f = R - 2*Lbd*(B/A)
    fR = 1 - 2*n*Lbd*(mu**(2*n))*(B/A)*(1/(R*A))
    fRR = 2*n*Lbd*(mu**(2*n))*(C/D)

    yaux1 = yH + t**(-3) + chi*t**(-4)
    yaux2 = t**(-3) + 2*chi*t**(-4)
    j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
    j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
    j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
    J1 = (1/t)*(1 + j1)
    J2 = (1/t)*(j2/t)
    J3 = (1/t)*(j3/t)
    dYH = - J1*YH - J2*yH - J3

    H = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
    dH = (R/(6*t*H)) - (2*H/t)

    gaux3 = (fRR/fR)*(k*(H0/100)/t)**2
    Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
    faux1 = 3*Geffn*H0**2
    faux2 = 2*t*t*H*H

    ddD_HS = - ((3/t) + (dH/H))*dD_HS + (faux1/faux2)*O_m*D_HS
    return [YH, dYH, dD_HS, ddD_HS]

def D_HS_n2(H0, O_m0, mu):
    y0 = [(1-O_m0)/O_m0, 0, 0.17, 1]
    sol_S = solve_ivp(contrast_HS_n2, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, mu))
    D1_S = sol_S.y[2]
    return D1_S


#######################################################################################



# Modelo f(Q) - 3
def Densidade_Q3(t, y, H0, O_m0, m):
    D_Q3 = y[0]
    dD_Q3 = y[1]

    O_m = O_m0*t**(-3)
    O_L = 1 - O_m0 - O_r0

    M = m*H0
       
    H_Q3 = H0*np.sqrt(O_m + O_L)
    dH_Q3 = -(3/2)*H0*(H0/H_Q3)*(O_m/t) # derivada de H com relação ao fator de escala
    
    Q = 6*(H_Q3)**2
    
    dfQ_3 = 1 + M*(Q**(-1/2)) / 2
    
    f1 = 3*(H0**2)*O_m
    f2 = 2*(t**2)*(H_Q3**2)*dfQ_3

    ddD_Q3 = - ((3/t) + (dH_Q3/H_Q3))*dD_Q3 + (f1/f2)*D_Q3  # equação do contraste
    return [dD_Q3, ddD_Q3]


def solD_fQ3(H0, O_m0, m):
    # Espaço de integração:
    t_span = [ti, 1]
    t = np.linspace(ti, 1, 1000)

    # Condições iniciais:
    y0 = [ti, 1]

    # Solução:
    sol_Q3 = solve_ivp(Densidade_Q3, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
    D_Q3 = sol_Q3.y[0]
    return D_Q3




# Modelo f(Q) - 2
def Densidade_Q2(t, y, H0, O_m0, m):
    D_Q2 = y[0]
    dD_Q2 = y[1]

    O_m = O_m0*t**(-3)

    M = m*H0
    M4 = M**4

    H_Q2 = np.sqrt( (H0**2)*O_m / 2 + (1/6)*np.sqrt(9*H0**4*O_m**2 + 3*M4) ) # eq de Friedmann minha
    dH_Q2 = ( (M**4 - 12*H_Q2**4)*3*H_Q2 ) / (2*t*(M**4 + 12*H_Q2**4) ) # obtida com a 1 eq de Friedmann minha

    Q = 6*(H_Q2**2)

    dfQ_2 = 1 - (M**4/Q**2)  # primeira derivada da f(Q)

    f1 = 3*(H0**2)*O_m
    f2 = 2*(t**2)*(H_Q2**2)*dfQ_2

    ddD_Q2 = - ((3/t) + dH_Q2/H_Q2)*dD_Q2 + ( (f1/f2)*D_Q2 )  # equação do contraste
    return [dD_Q2, ddD_Q2]

def solD_fQ2(H0, O_m0, m):
    # Espaço de integração:
    t_span = [ti, 1]
    t = np.linspace(ti, 1, 1000)

    # Condições iniciais:
    y0 = [ti, 1]

    # Solução:
    sol_Q2 = solve_ivp(Densidade_Q2, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
    D_Q2 = sol_Q2.y[0]
    return D_Q2


# plotando o contraste x z

plt.plot(z, D_RG, color='blue', linewidth = 3, label='$\Lambda$CDM', linestyle='--')
plt.plot(z, D_RG_w1, color='red', linewidth = 2, label='$\omega$CDM')
plt.plot(z, D_RG_w, color='darkgoldenrod', linewidth = 2, label='$\omega_0 \omega_a$CDM')
plt.plot(z, D_OKCDM(0.317, 0.2), color='green', label='$\Omega_k$-CDM')


#plt.plot(z, D_S_n1(67.1,0.328,0.589), color='orange', linewidth = 2, label='Starobinski (n=1)', linestyle = '-.')
#plt.plot(z, D_S_n2(66.4,0.350,1.047), color='deeppink', linewidth = 2.8, label='Starobinski (n=2)', linestyle = '-.')
#plt.plot(z, D_HS_n1(69.7,0.269,82), color='purple', linewidth = 2, label='Hu-Sawicki (n=1)')
#plt.plot(z, D_HS_n2(66.8,0.327,104), color='magenta', linewidth = 2, label='Hu-Sawicki (n=2)')
#plt.plot(z, sol_DAB(67.3, 0.332, 1.98), color='black', linewidth = 2, label='$R^2$_AB')

#plt.plot(z, solD_fQ3(66.9, 0.347, 2.0), color='maroon', label='$F_1(Q)$', linewidth = 2)
#plt.plot(z, solD_fQ2(67.4, 0.315, 2.0331), color='slategray', label='$F_2(Q)$', linewidth = 2)

plt.plot(xi, delta_rec-0.21, color='navy', linewidth = 2, label='GP-0.21', linestyle='dotted' )


plt.fill(np.concatenate([xi, xi[::-1]]),
        np.concatenate([delta_rec-0.21 - 1.00 * sig_d,
                        (delta_rec-0.21 + 1.00 * sig_d)[::-1]]),
        alpha=.5, color = 'cornflowerblue', ec='None')

plt.fill(np.concatenate([xi, xi[::-1]]),
        np.concatenate([delta_rec-0.21 - 1.9600 * sig_d,
                       (delta_rec-0.21 + 1.9600 * sig_d)[::-1]]),
        alpha=.25, color = 'dodgerblue', ec='None')


#plt.fill(np.concatenate([xi, xi[::-1]]),
#        np.concatenate([delta_rec-0.21 - 2.997 * sig_d,
#                        (delta_rec-0.21 + 2.997 * sig_d)[::-1]]),
#        alpha=.5, color = 'dodgerblue', ec='None')

plt.legend(prop={'size':9.5})
plt.ylim(0.25,1)
plt.xlim(0,1)
plt.xlabel('$z$', fontsize=20)
plt.ylabel('$\delta(z)$', fontsize=15)
#plt.savefig('delta(z)_comparação_GR.pdf', dpi=520, format='pdf', bbox_inches='tight')
plt.show()


