# -*- coding: utf-8 -*-
"""dl_reconstruction_covariance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J-KkcW1b8ZGUMN9NSZd6oyUPcE1ZPMrn
"""

import matplotlib.pyplot as plt
import numpy as np
from numpy import loadtxt, savetxt
from gapp import gp
plt.rcParams['text.usetex'] = True
import pandas as pd
import scipy as sp

# 1) BAIXANDO O ARQUIVO


# --------------- Dados SNe --------------- #
#df= pd.read_csv('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES.dat', sep=' ')
#df= pd.read_csv('/content/Pantheon+SH0ES.dat', sep=' ')
#df=df.sort_values("zCMB", ascending=False)
#df['acmb'] = 1/(1+df["zCMB"])
#a_sn = df['acmb']
#y_sn = df["m_b_corr"]

df = np.genfromtxt('Pantheon+SH0ES.dat', names=True)
zCMB = df["zCMB"]
mu = df["MU_SH0ES"]
dl= 10 ** ((mu/5) - 5)


mcov = np.loadtxt('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
#mcov = np.loadtxt('/content/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
cov = np.reshape(mcov, (1701, 1701))
Icov=np.linalg.inv(cov)
Icov

#print(cov)

#print(dl)

cov_dl =  ( ( (1/5)*np.log(10) )**2 ) * (dl**2) * (cov) 



#data = np.genfromtxt('/home/usuario/Documentos/Dados/dl_snia.dat', delimiter='\t')

#zCMB = data[:, 0]

#dl= np.power(10, ((mu-25)/5))
#dl = data[:, 1]
#dlerr = data[:, 2]



# Remove valores repetidos de zCMB, mantendo a primeira ocorrência
#unique_zCMB, unique_indices = np.unique(zCMB, return_index=True)

# Filtra os dados para manter apenas as linhas correspondentes aos valores únicos de zCMB
#unique_dl = dl[unique_indices]
#unique_dlerr = sig_dl[unique_indices]

#print(len(unique_zCMB))
#print(len(unique_dl))
#print(len(unique_dlerr))


# definindo constantes
c = 2.9*10**5 # velocidade da luz
h0 = 70 #km/s/Mpc


######## PROCESSO GAUSSIANO USANDO GAPP #################

# nomeando
x_gapp = zCMB
y_gapp = dl
e = cov_dl


# xmin, xmax and nstar are interpreted as two-dimensional vectors
xmin = 0
xmax = 5.0
nstar = 1000


# initial values of the hyperparameters of the squared-exponential covariance function
initheta = [2.0, 2.0]

# initialization of the Gaussian Process
g = gp.GaussianProcess(x_gapp, y_gapp, e, cXstar=(xmin, xmax, nstar))

# training of the hyperparameters and reconstruction of the function
(rec, theta) = g.gp(theta=initheta)

xi = rec[:, 0]

y_pred = rec[:, 1]
sigma  = rec[:, 2]

y_pred_95_less = y_pred - 1.9600*sigma
y_pred_95_plus = y_pred + 1.9600*sigma



# salvando os dados

N =  xi, y_pred, sigma

np.savetxt('dlz_recon_covariance.csv', np.transpose(N), delimiter=', ')


# Plot the function, the prediction and the 95% confidence interval
plt.figure()
plt.tick_params(labelsize=14, color='purple')
plt.errorbar(x_gapp, y_gapp, e, fmt='r.', color='purple', markersize=10, label='Data')
plt.plot(xi, y_pred, color = 'green', label='Prediction', linestyle="--")
plt.fill(np.concatenate([xi, xi[::-1]]),
         np.concatenate([y_pred - 1.9600 * sigma,
                        (y_pred + 1.9600 * sigma)[::-1]]),
         alpha=.5, color = 'lightgreen', ec='None')

# legenda, label e título
plt.xlabel('$z$', fontsize=15)
plt.ylabel('$D_L(z)$', fontsize=15)
plt.legend(loc='best')
plt.savefig('dl_recon_covariance.pdf', format='pdf', bbox_inches='tight')
plt.show()

