# -*- coding: utf-8 -*-
"""EqContraste_OkCDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLe4OpdDTAzowSeK2UewXlYnBx5BmF6R
"""

# Bibliotecas:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
from scipy.integrate import cumtrapz
import sympy as sp

# constantes
H0 = 67.4
O_m0 = 0.3485
O_k0 = -0.056

# Modelo O_k-CDM:

a = np.linspace(0.17, 1, 1000)

z_LC = (1/a) - 1

O_L1 = 1 - O_m0 - O_k0

H_LC = H0*np.sqrt(O_m0*(a**(-3)) + O_L1 + O_k0*(a**(-2)))

Om = O_m0*(a**(-3)) / ( (H_LC/H0)**2 )

f_LC = Om**0.55

x1 = cumtrapz(f_LC, x = np.log(a), initial = 0.001)

delta = np.exp(x1)

plt.plot(z_LC, delta, color='green', label='$\Omega_k$-CDM')
plt.xlabel('$z$', fontsize=15)
plt.ylabel('$\delta(z)$', fontsize=15)
plt.legend()
plt.show()