# -*- coding: utf-8 -*-
"""f_Starobinski.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzaSUMr251I2bJINHxGNeSgpnhU9suF0
"""

# Bibliotecas:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Parâmetros:
H0 = 67.4
O_m0 = 0.315
O_r0 = 0
b = 2
k = 0.125

p = 0.17
t = np.linspace(p, 1, 1000)
z = (1/t) - 1


# Modelo Starobinski
def f_S(t, y, lbd, n): # lbd é o parâmetro lambda
    yH = y[0]
    YH = y[1]        # YH = dyH/da
    fg_s = y[2]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)

    chi = O_r0/O_m0
    ms = (H0**2)*O_m0
    O_L = 1 - O_m0

    R = 3*ms*(4*yH + t*YH + t**(-3))

    Rs = 6*(H0**2)*(1 - O_m0)/lbd
    star = 1 + (R/Rs)**2

    f = R + lbd*Rs*( (star**(-n)) - 1 )
    fR = 1 - 2*n*lbd*(R/Rs)*((star)**(-(n+1)))
    fRR = (2*n*lbd/Rs)*( 2*(n+1)*((R/Rs)**2)*(star**(-n-2)) - (star**(-n-1)) )

    yaux1 = yH + t**(-3) + chi*t**(-4)
    yaux2 = t**(-3) + 2*chi*t**(-4)

    j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
    j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
    j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
    J1 = (1/t)*(1 + j1)
    J2 = (1/t)*(j2/t)
    J3 = (1/t)*(j3/t)

    dYH = - J1*YH - J2*yH - J3

    H_S = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
    dH_S = (R/(6*t*H_S)) - (2*H_S/t)

    gaux3 = (fRR/fR)*(k*(H0/100)/t)**2
    Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)

    fAB1 = 3*Geffn*H0**2
    fAB2 = 2*t*t*H_S*H_S

    dfg_s =  - ((dH_S/H_S) + ((2 + fg_s)/t))*fg_s + (3/2)*(H0/H_S)**2*Geffn*(O_m/t)
    return [YH, dYH, dfg_s]



# Integração:
t_span =[0.17, 1]
t = np.linspace(0.17, 1, 1000)



# Condições iniciais:
ti = 0.17
Hi = H0*np.sqrt(O_m0*ti**(-3) + (1 - O_m0))
O_mi = O_m0*ti**(-3)
O_ri = O_r0*ti**(-4)
O_L = 1 - O_m0
Hi = H0*np.sqrt(O_mi + O_ri + O_L)
dHi = - ((H0*H0)/(2*ti*Hi))*(3*O_mi + 4*O_ri)
fgi = ((H0/Hi)**2 * O_mi)**(6/11)  # no passado, todas as teorias f(R) recaem na RG
y0 = [Hi, dHi, fgi]


# Solução
lbd = 1 
n = 1
sol_s = solve_ivp(f_S, t_span, y0, t_eval=t, args=(lbd, n), method='LSODA', rtol=1e-6)
fg_S = sol_s.y[2]


plt.plot(z, fg_S, color='orange', linewidth=2, label='Starobinski (n=1)')
plt.legend()
plt.xlabel('z')
plt.ylabel('$f(z)$')
#plt.savefig('f_Starobinski(n=2).png', dpi=520, format='png', bbox_inches='tight')
plt.show()



