# -*- coding: utf-8 -*-
"""growth_function_Fernanda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abD9LbxPgEH-5FhQgaGLUTYcZWAuKmR4
"""

# Bibliotecas:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Parâmetros:
O_r0 = 0
mu = 10**(-7)
k = 0.125              # r = 8 Mpc/h
#n=1
ti = 0.17
tf = 1.0
p = 1000
t = np.linspace(ti, tf, p)
z = (1/t) - 1

# Modelo LCDM:
def fgRG(t, y, H0, O_m0):
    fg_RG  = y[0]

    O_m = O_m0*t**(-3)
    O_r = O_r0*t**(-4)
    O_L = 1 - O_m0

    H_RG = H0*np.sqrt(O_m + O_r + O_L)
    dH_RG = - (H_RG/t) - 0.5*(H0/t)*(H0/H_RG)*(O_m + 2*O_r - 2*O_L)

    faux1 = 3*H0**2
    faux2 = 2*(t**2)*(H_RG**2)

    dfg_RG = - ((dH_RG/H_RG) + ((2+fg_RG)/t))*fg_RG + (3/2)*((H0/H_RG)**2)*(O_m/t)
    return dfg_RG

def fgLsol(H0, O_m0):
  # Integração:
  t_span =[ti, tf]
  # Condições iniciais:
  Hi = H0*np.sqrt(O_m0*ti**(-3) + (1 - O_m0))
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  fgi = ((H0/Hi)**2 * O_mi)**(6/11)
  y0 = [fgi]
  # Solução RG:
  solRG = solve_ivp(fgRG, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0))
  fg_RG = solRG.y[0]
  return fg_RG


######################################################################

# D(t) according to the HS model:
def growth_HS(t, y, H0, O_m0, c2, n):
  yH = y[0]
  YH = y[1]
  fg_HS = y[2]

  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)
  chi = O_r0/O_m0
  ms = (H0**2)*O_m0
  O_L = 1 - O_m0
  R = 3*ms*(4*yH + t*YH + t**(-3))

  c1 = 6*c2*(O_L/O_m0)
  xn1 = (R/ms)**n
  xn2 = c1/(ms**n)
  xn3 = (n+1)*(c2/ms)*R**(2*(n-1))
  xn4 = (n-1)*R**(n-2)
  xn5 = ((c2*xn1) + 1)
  f = R - ms*((c1*xn1)/((c2*xn1) + 1))
  fR = 1 - n*xn2*ms*((R**(n-1))/(xn5**2))
  fRR = n*xn2*ms*( (xn3 - xn4)/(xn5**3))

  yaux1 = yH + t**(-3) + chi*t**(-4)
  yaux2 = t**(-3) + 2*chi*t**(-4)
  j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
  j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
  j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
  J1 = (1/t)*(1 + j1)
  J2 = (1/t)*(j2/t)
  J3 = (1/t)*(j3/t)

  dYH = - J1*YH - J2*yH - J3

  H_HS = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
  dH_HS = (R/(6*t*H_HS)) - (2*H_HS/t)

  gaux3 = (fRR/fR)*(k/t)**2
  Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
  faux1 = 3*Geffn*H0**2
  faux2 = 2*t*H_HS*H_HS

  dfg_HS = - ((dH_HS/H_HS) + ((2 + fg_HS)/t))*fg_HS + (faux1/faux2)*O_m

  return [YH, dYH, dfg_HS]

def fg_HS(H0, O_m0, c2, n):
  # Integração:
  t_span =[ti, tf]

  # Condições iniciais:
  Hi = H0*np.sqrt(O_m0*ti**(-3) + (1 - O_m0))
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  fgi = ((H0/Hi)**2 * O_mi)**(6/11)
  y0 = [(1-O_m0)/O_m0, 0, fgi]

  # Solução RG:
  sol_HS = solve_ivp(growth_HS, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, c2, n))
  fg_HS = sol_HS.y[2]
  return fg_HS


######################################################################################

# D(t) according to the Starobinsky model:
def growth_S(t, y, H0, O_m0, lbd, n):
  yH = y[0]
  YH = y[1]
  fg_S = y[2]

  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)
  chi = O_r0/O_m0
  ms = (H0**2)*O_m0
  O_L = 1 - O_m0
  R = 3*ms*(4*yH + t*YH + t**(-3))

  Rs = 6*(H0**2)*O_L/lbd
  star = 1 + (R/Rs)**2
  f = R + lbd*Rs*((star**(-n)) - 1)
  fR = 1 - 2*n*lbd*(R/Rs)*((star)**(-(n+1)))
  fRR = (2*n*lbd/Rs)*(2*(n+1)*((R/Rs)**2)*(star**(-n-2)) - (star**(-n-1)))

  yaux1 = yH + t**(-3) + chi*t**(-4)
  yaux2 = t**(-3) + 2*chi*t**(-4)
  j1 = 4 + (1/yaux1)*(1-fR)/(6*ms*fRR)
  j2 = (1/yaux1)*(2-fR)/(3*ms*fRR)
  j3 = - 3*t**(-3) - (((1-fR)*yaux2 + (R-f)/(3*ms))/yaux1)*(1/(6*ms*fRR))
  J1 = (1/t)*(1 + j1)
  J2 = (1/t)*(j2/t)
  J3 = (1/t)*(j3/t)

  dYH = - J1*YH - J2*yH - J3

  H_S = np.sqrt(ms*(yH + (1/t)**3 + chi*(1/t)**4))
  dH_S = (R/(6*t*H_S)) - (2*H_S/t)

  gaux3 = (fRR/fR)*(k/t)**2
  Geffn = (1/(fR))*(1 + 4*gaux3)/(1 + 3*gaux3)
  faux1 = 3*Geffn*H0**2
  faux2 = 2*t*H_S*H_S

  dfg_S = - ((dH_S/H_S) + ((2 + fg_S)/t))*fg_S + (faux1/faux2)*O_m

  return [YH, dYH, dfg_S]

def fg_S(H0, O_m0, lbd, n):
  # Integração:
  t_span =[ti, tf]

  # Condições iniciais:
  Hi = H0*np.sqrt(O_m0*ti**(-3) + (1 - O_m0))
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  fgi = ((H0/Hi)**2 * O_mi)**(6/11)
  y0 = [(1-O_m0)/O_m0, 0, fgi]

  # Solução RG:
  sol_S = solve_ivp(growth_S, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, lbd, n))
  fg_S = sol_S.y[2]
  return fg_S

plt.plot(z, fg_HS(70, 0.3, 2, 1), color='purple', linewidth = 1.5, label='Hu-Sawicki model (n=1)')
plt.plot(z, fg_HS(70, 0.3, 2, 2), color='magenta', linewidth = 1.5, label='Hu-Sawicki model (n=2)')
plt.plot(z, fg_S(70, 0.3, 2, 1),  color='orange', linewidth = 1.5, label='Starobinsky model (n=1)', linestyle = '-.')
plt.plot(z, fg_S(70, 0.3, 2, 2),  color='darkgoldenrod', linewidth = 1.5, label='Starobinsky model (n=2)', linestyle = '-.')
plt.plot(z, fgLsol(70, 0.3),   color='blue',  linewidth = 1.5, label='$\Lambda$CDM model', linestyle = '--')
plt.legend(loc='lower right')
plt.title('Resolvendo a eq. dif. para $f(z)$')
plt.xlabel('$z$')
plt.ylabel('$f(z)$')
#plt.xlim(-0.1, 1.2)
#plt.ylim(0.5, 0.925)
#plt.savefig('f(z)_Bruno2.png', dpi=520, format='png', bbox_inches='tight')
plt.show()

