# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxRrnY9weWOo1ukD4Ttjri0n8VYd_w_e
"""

# Libraries:
import numpy as np
import scipy as sp
import pandas as pd
import math
from scipy import integrate
from scipy.integrate import solve_ivp
from multiprocessing import Pool
import emcee
import time
from chainconsumer import ChainConsumer
import corner
import matplotlib.pyplot as plt

# Fiducial:
ti = 0.2
tf = 1.0
p = 1000
O_r0 = 0
t_span = [ti, tf]
t = np.linspace(ti, tf, p)
z = (1/t) - 1

# Dados:

# --------------- Dados CC --------------- #
aCC = [0.3372681281618887, 0.36363636363636365, 0.39525691699604737,
          0.41152263374485604, 0.4231908590774439, 0.4347826086956522,
          0.4909180166912126, 0.5263157894736842, 0.5319148936170213,
          0.5333333333333333, 0.5614823133071308, 0.5952380952380952,
          0.6277463904582549, 0.6756756756756757, 0.6764526821348847,
          0.6802721088435374, 0.689797889218459, 0.7019021548396153,
          0.7140816909454443, 0.7142857142857143, 0.7245326764237068,
          0.7396449704142013, 0.78125, 0.7874015748031495, 0.8333333333333334,
          0.8340283569641367, 0.8481764206955046, 0.8547008547008548,
          0.8928571428571428, 0.9174311926605504, 0.9345794392523364]

HCC = [186.5, 202.0, 140.0, 177.0, 160.0, 168.0, 154.0, 117.0, 90.0, 125.0,
          105.0, 92.0, 104.0, 97.0, 80.9, 89.0, 92.8, 87.1, 77.0, 95.0, 83.0,
          83.0, 88.8, 77.0, 72.9, 75.0, 75.0, 83.0, 68.6, 69.0, 69.0]

sigmaCC = [50.4, 40.0, 14.0, 18.0, 33.6, 17.0, 20.0, 23.0, 40.0, 17.0,
              12.0, 8.0, 13.0, 62.0, 9.0, 49.6, 12.9, 11.2, 10.2, 17.0, 13.5,
              14.0, 36.6, 14.0, 29.6, 5.0, 4.0, 8.0, 26.2, 12.0, 19.6]

CC = pd.DataFrame({"aCC":aCC, "HCC":HCC, "sigmaCC":sigmaCC})

acc = CC['aCC']
zcc = 1/CC['aCC'] - 1
y_cc = CC['HCC']
yerr_cc = CC['sigmaCC']
#-------------------------------------------------------------------------------

# --------------- Dados RSD --------------- #
aRSD = [0.340, 0.403, 0.417, 0.488, 0.506, 0.541, 0.568, 0.575, 0.578, 0.588,
        0.629, 0.637, 0.694, 0.725, 0.758, 0.870, 0.909, 0.937, 0.976, 0.980]

fRSD = [0.364, 0.30, 0.482, 0.280, 0.379, 0.52, 0.440, 0.50, 0.437, 0.473, 0.488,
        0.453, 0.413, 0.497, 0.384, 0.53, 0.37, 0.423, 0.39, 0.398]

sigmaRSD = [0.106, 0.13, 0.116, 0.080, 0.176, 0.10, 0.040, 0.11, 0.072, 0.041,
            0.060, 0.022, 0.080, 0.045, 0.095, 0.16, 0.13, 0.055, 0.11, 0.065]

RSD = pd.DataFrame({'aRSD':aRSD, 'fRSD':fRSD, 'sigmaRSD':sigmaRSD})

arsd = RSD['aRSD']
zrsd = 1/RSD['aRSD'] - 1
y_rsd = RSD['fRSD']
yerr_rsd = RSD['sigmaRSD']
#-------------------------------------------------------------------------------

# --------------- Dados SNe --------------- #
#df= pd.read_csv('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES.dat', sep=' ')
df= pd.read_csv('/content/Pantheon+SH0ES.dat', sep=' ')
df=df.sort_values("zCMB", ascending=False)
df['acmb'] = 1/(1+df["zCMB"])
a_sn = df['acmb']
y_sn = df["m_b_corr"]

mcov = np.loadtxt('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
#mcov = np.loadtxt('/content/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
cov = np.reshape(mcov, (1701, 1701))
Icov=np.linalg.inv(cov)
Icov
#-------------------------------------------------------------------------------

def Hubble_Q2(acc, H0, O_m0, m):
  O_m = O_m0 * acc**(-3)
  M = m*H0
  M4 = M**4
  c0 = 3*(H0**2) #- M4/(4*(H0**2))
  H1 = c0*O_m
  H2 = H1**2 + 3*M4

  H_Q2 = np.sqrt((H1 + np.sqrt(H2))/6)
  return H_Q2

#print(Hubble_Q2(acc, 70, 0.3, 1.6))

# Modelo f(Q) - 2
def contrast_Q2(t, y, H0, O_m0, m):
    D_Q2 = y[0]
    dD_Q2 = y[1]

    O_m = O_m0 * t**(-3)
    #O_r = O_r0 * t**(-4)
    #Omega = O_m + O_r

    M = m*H0
    M4 = M**4

    c0 = 3*(H0**2) #- M4/(4*(H0**2))
    H1 = c0*O_m
    H2 = H1**2 + 3*M4

    H_Q2 = np.sqrt((H1 + np.sqrt(H2))/6)

    HQ4 = H_Q2**4

    c1 = (M4/(12*HQ4)) + 1

    dH_Q2 = - (3/2)*(H0/t)*(H0/H_Q2)*(O_m/c1)

    Q = 6 * (H_Q2**2)
    dfQ_2 = 1 - (M4/(Q**2))

    f1 = 3 * H0**2 * O_m
    f2 = 2 * t**2 * H_Q2**2 * dfQ_2

    ddD_Q2 = - ((3/t) + dH_Q2/H_Q2)*dD_Q2 + ( (f1/f2)*D_Q2 )  # equação do contraste
    return [dD_Q2, ddD_Q2]

def D_Q2(H0, O_m0, m):
    y0 = [0.2, 1]
    sol_Q2 = solve_ivp(contrast_Q2, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
    delta_Q2 = sol_Q2.y[0]
    return delta_Q2

#def Dnorm_Q2(H0, O_m0, m):
#    y0 = [ti, 1]
#    sol_Q2 = solve_ivp(contrast_Q2, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
#    delta_Q2 = sol_Q2.y[0]/D_Q2(H0, O_m0, m)[999]
#    return delta_Q2

# fsig8(t) from F(Q) - model 2:
def fs8_Q2(arsd, H0, O_m0, sig80, m):
  y0 = [0.2, 1]
  sol_Q2 = solve_ivp(contrast_Q2, t_span, y0, t_eval=arsd, method='LSODA', args=(H0, O_m0, m))
  dD_Q2 = sol_Q2.y[1]
  fs8_GR = sig80*arsd*(dD_Q2/D_Q2(H0, O_m0, m)[999])
  return fs8_GR

#print(fs8_Q2(70, 0.3, 0.8, 1.6))

# m_B(t) from F(Q) - 2 model:
def Hubble_Q2t(t, H0, O_m0, m):
  O_m = O_m0 * t**(-3)
  M = m*H0
  M4 = M**4
  c0 = 3*(H0**2) #- M4/(4*(H0**2))
  H1 = c0*O_m
  H2 = H1**2 + 3*M4

  H_Q2 = np.sqrt((H1 + np.sqrt(H2))/6)
  return H_Q2

def Int1_Q2(H0, O_m0, m):
  y = 1/((t**2)*Hubble_Q2(t, H0, O_m0, m))
  IntQ2 = integrate.cumulative_trapezoid(y, t, initial=0)
  return IntQ2

def Int_Q2(H0, O_m0, m):
  y = 1/((t**2)*Hubble_Q2t(t, H0, O_m0, m))
  IntQ2 = Int1_Q2(H0, O_m0, m)[0] + integrate.cumulative_trapezoid(y, t, initial=0)
  return IntQ2

# Primitive:
def Int_FQ2(H0, O_m0, m):
  IntFQ2 = Int_Q2(H0, O_m0, m)[999] - Int_Q2(H0, O_m0, m)
  return IntFQ2

def Int_Q2_interp(H0, O_m0, m):
  x_interp = df['acmb']
  y_interp = np.interp(x_interp, t, Int_FQ2(H0, O_m0, m))
  return y_interp

def Lumi_Q2(H0, O_m0, m):
  dL_Q2 = (299792.458/df['acmb'])*(Int_Q2_interp(H0, O_m0, m))
  return dL_Q2

def mag_Q2(a_sn, H0, O_m0, Mb, m):
  mb_Q2 = 5*np.log10(Lumi_Q2(H0, O_m0, m)) + 25 + Mb
  return mb_Q2

#print(mag_Q2(a_sn, 70, 0.3, -19.412, 1.6))

# --------------- chi2 CC --------------- #
def chiCC(acc, H0, O_m0, m, y_cc, yerr_cc):
    ycc_model = Hubble_Q2(acc, H0, O_m0, m)
    return np.sum( ((y_cc - ycc_model)/ yerr_cc) ** 2 )

def chi2cc(theta_cc, acc, y_cc, yerr_cc):
    H0, O_m0, m = theta_cc
    return chiCC(acc, H0, O_m0, m, y_cc, yerr_cc)

print(chiCC(acc, 70, 0.3, 1.6, y_cc, yerr_cc))
#-------------------------------------------------------------------------------

# --------------- chi2 RSD --------------- #
def chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd):
    yrsd_model = fs8_Q2(arsd, H0, O_m0, sig80, m)
    return np.sum( ( (y_rsd - yrsd_model)/yerr_rsd ) ** 2 )

def chi2rsd(theta_rsd, arsd, y_rsd, yerr_rsd):
    H0, O_m0, sig80, m = theta_rsd
    return chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd)

print(chiRSD(arsd, 70, 0.3, 0.75, 1.8, y_rsd, yerr_rsd))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe --------------- #
def delta(a_sn, H0, O_m0, Mb, m, y_sn):
  mb_model = mag_Q2(a_sn, H0, O_m0, Mb, m)
  delta = y_sn - mb_model
  return delta

def chi2_SN(a_sn, H0, O_m0, Mb, m, y_sn, Icov):
  chisq = np.sum(np.dot(np.dot(delta(a_sn, H0, O_m0, Mb, m, y_sn), Icov), delta(a_sn, H0, O_m0, Mb, m, y_sn)))
  return chisq

def chisq_SN(theta_sn, a_sn, y_sn, Icov):
    H0, O_m0, Mb, m = theta_sn
    return chi2_SN(a_sn, H0, O_m0, Mb, m, y_sn, Icov)

print(chisq_SN([70, 0.3, -19.253, 1.6], a_sn, y_sn, Icov))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe+CC+RSD --------------- #

def chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, m, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    chicc = chiCC(acc, H0, O_m0, m, y_cc, yerr_cc)
    chirsd = chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd)
    chisn = chi2_SN(a_sn, H0, O_m0, Mb, m, y_sn, Icov)
    return  chicc + chirsd + chisn

def chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, m = theta
    return chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, m, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(chi2_tot([70, 0.3, 0.8, -19.253, 1.6], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))
#-------------------------------------------------------------------------------

# likelihood:
def lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, m = theta
    return -0.5 * chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(lnlike([70, 0.3, 0.8, -19.253, 1.6], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

def lnprior(theta):
    H0, O_m0, sig80, Mb, m = theta
    if 54 < H0 < 76 and 0.1 < O_m0 < 0.5 and 0.6 < sig80 < 0.9 and -20.2 < Mb < -19 and 0 < m < 4:
        return 0.0
    return -np.inf

def lnprob(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    lp = lnprior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(lnprob([70, 0.3, 0.72, -19.253, 1.8], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

data = (acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)
nwalkers =  40   #The number of walkers in the ensemble.
niter = 10000 #número de interações
initial = np.array([70, 0.3, 0.8, -19.253, 1]) #chute inicial para os parâmetros livres
ndim = len(initial) #Number of dimensions in the parameter space.
p0 = [np.array(initial) + 1e-4 * np.random.randn(ndim) for i in range(nwalkers)]

# RUN MCMC:
with Pool() as pool:
    def main(p0,nwalkers,niter,ndim,lnprob,data):
        sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=data, pool=pool)

        print("Running burn-in...")
        p0, _, _ = sampler.run_mcmc(p0, 1500, progress=True)
        sampler.reset()

        print("Running production...")
        pos, prob, state = sampler.run_mcmc(p0, niter, progress=True)

        return sampler, pos, prob, state

    sampler, pos, prob, state = main(p0,nwalkers,niter,ndim,lnprob,data)

burnin = 1500
like_model =  sampler.get_log_prob(discard=burnin, flat=False)
chi2_model = -2*like_model

np.savetxt('log_pro_FQ2_Fulldata.txt', like_model, fmt="%s")
print(chi2_model.min())

samples1 = sampler.flatchain
samples1[np.argmax(sampler.flatlnprobability)]
np.savetxt("Resultados_FQ2_Fulldata.txt", samples1, fmt="%s")

labels = ['H0','O_m0', 'sig80', 'Mb', 'm']
fig = corner.corner(samples1,show_titles=True,labels=labels,plot_datapoints=True)