# -*- coding: utf-8 -*-
"""MCMC_Fernanda_Completo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAf9QibntI5McERMHSL3-NTmJFQ56VHX
"""

import pandas as pd
import numpy as np
import scipy as sp
import math
from scipy.integrate import solve_ivp
from scipy import integrate
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from multiprocessing import Pool
import emcee
import time
import corner
#from chainconsumer import ChainConsumer

# Fiducial:
ti = 0.2
tf = 1.0
p = 1000
O_r0 = 0
Delta = 10**(-7)
n = 1
t_span = [ti, tf]
t = np.linspace(ti, tf, p)
z = (1/t) - 1
w = -1
k = 0.125
c = 1

# Dados:

# --------------- Dados CC --------------- #
aCC = [0.3372681281618887, 0.36363636363636365, 0.39525691699604737,
          0.41152263374485604, 0.4231908590774439, 0.4347826086956522,
          0.4909180166912126, 0.5263157894736842, 0.5319148936170213,
          0.5333333333333333, 0.5614823133071308, 0.5952380952380952,
          0.6277463904582549, 0.6756756756756757, 0.6764526821348847,
          0.6802721088435374, 0.689797889218459, 0.7019021548396153,
          0.7140816909454443, 0.7142857142857143, 0.7245326764237068,
          0.7396449704142013, 0.78125, 0.7874015748031495, 0.8333333333333334,
          0.8340283569641367, 0.8481764206955046, 0.8547008547008548,
          0.8928571428571428, 0.9174311926605504, 0.9345794392523364]

HCC = [186.5, 202.0, 140.0, 177.0, 160.0, 168.0, 154.0, 117.0, 90.0, 125.0,
          105.0, 92.0, 104.0, 97.0, 80.9, 89.0, 92.8, 87.1, 77.0, 95.0, 83.0,
          83.0, 88.8, 77.0, 72.9, 75.0, 75.0, 83.0, 68.6, 69.0, 69.0]

sigmaCC = [50.4, 40.0, 14.0, 18.0, 33.6, 17.0, 20.0, 23.0, 40.0, 17.0,
              12.0, 8.0, 13.0, 62.0, 9.0, 49.6, 12.9, 11.2, 10.2, 17.0, 13.5,
              14.0, 36.6, 14.0, 29.6, 5.0, 4.0, 8.0, 26.2, 12.0, 19.6]

CC = pd.DataFrame({"aCC":aCC, "HCC":HCC, "sigmaCC":sigmaCC})

acc = CC['aCC']
zcc = 1/CC['aCC'] - 1
y_cc = CC['HCC']
yerr_cc = CC['sigmaCC']
#-------------------------------------------------------------------------------

# --------------- Dados RSD --------------- #
aRSD = [0.33967391, 0.339673911, 0.41666667, 0.44843049, 0.48780488, 0.50556117, 0.53763441, 0.57803468, 0.5790388, 0.58139535,
        0.6097561, 0.62111801, 0.625, 0.6251, 0.62893082, 0.63694268, 0.64102564, 0.65789474, 0.66225166, 0.67567568, 0.69444444,
        0.694444441, 0.71428571, 0.72463768,  0.73529412, 0.75757576, 0.76335878, 0.8, 0.84745763, 0.86956522, 0.90909091, 0.97087379,
        0.98039216, 0.980392161, 0.999001]

fRSD = [0.364, 0.342, 0.482, 0.385, 0.28, 0.379, 0.46, 0.437, 0.296, 0.454, 0.379, 0.436, 0.49, 0.39, 0.452, 0.501, 0.472, 0.483,
         0.458 , 0.458, 0.426, 0.413, 0.461, 0.497, 0.409, 0.427, 0.384, 0.3512, 0.36, 0.49, 0.37, 0.404, 0.428, 0.314, 0.505]

sigmaRSD = [0.106, 0.07, 0.116, 0.099, 0.08, 0.176, 0.09, 0.072, 0.0765, 0.139, 0.054, 0.034, 0.12, 0.063, 0.061,  0.051, 0.063, 0.075,
           0.038, 0.063, 0.062, 0.08, 0.086, 0.045, 0.098, 0.056, 0.083, 0.0583, 0.09, 0.145, 0.13, 0.0815, 0.0465, 0.048, 0.085]


RSD = pd.DataFrame({'aRSD':aRSD, 'fRSD':fRSD, 'sigmaRSD':sigmaRSD})

arsd = RSD['aRSD']
zrsd = 1/RSD['aRSD'] - 1
y_rsd = RSD['fRSD']
yerr_rsd = RSD['sigmaRSD']
#-------------------------------------------------------------------------------

# --------------- Dados SNe --------------- #
df= pd.read_csv('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES.dat', sep=' ')
#df= pd.read_csv('/content/Pantheon+SH0ES.dat', sep=' ')
df=df.sort_values("zCMB", ascending=False)
df['acmb'] = 1/(1+df["zCMB"])
a_sn = df['acmb']
y_sn = df["m_b_corr"]

mcov = np.loadtxt('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
#mcov = np.loadtxt('/content/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
cov = np.reshape(mcov, (1701, 1701))
Icov=np.linalg.inv(cov)
Icov
#-------------------------------------------------------------------------------

# H(t) para o modelo R2-AB:
def Hubble(t, y, H0, O_m0, b):
  H  =  y[0]
  dH  = y[1]
  ddH = y[2]

  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)

  R_vac = 12*H0**2
  e_AB = R_vac/np.log(1 + np.exp(2*b))
  M2 = e_AB/Delta

  R = 6*H*(2*H + t*dH)
  alpha = (R/e_AB) - b
  if abs(alpha) < 15:
    s = 1/np.cosh(alpha)
  else:
    s = 0

  A = H0*H0*(3*O_m + 4*O_r)
  B = t*H*dH*(np.tanh(alpha) + 1)
  C = 4*t*H*H*dH*(t*dH + 2*H)/M2
  if abs(alpha) < 15:
    D = ((6*t*t*H*H)/e_AB)*(((5*dH/t) + (dH*dH/H) +ddH)**2)*np.tanh(alpha)*s*s
    E = 6*(t**3)*(H**3)*((1/(3*M2)) + (0.5*s*s/e_AB))
  else:
    D = 0
    E = 6*(t**3)*(H**3)/(3*M2)

  F = (11*dH*dH/(t*H)) + (dH*dH*dH/(H*H)) + (6*ddH/t) + (4*dH*ddH/H)

  dddH = - ((A + B + C - D)/E) - F
  return [dH, ddH, dddH]

def solHCC(acc, H0, O_m0, b):
  t_span = [0.2, 1]
  ti = 0.2
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  Hi = H0*np.sqrt(O_mi + O_ri + O_L)
  dHi = - ((H0*H0)/(2*ti*Hi))*(3*O_mi + 4*O_ri)
  ddHi = 0.5*(H0/(ti*Hi))**2*(Hi + ti*dHi)*(3*O_mi + 4*O_ri) + 0.5*(H0/(ti*Hi))**2*Hi*(9*O_mi + 16*O_ri)
  y0 = [Hi, dHi, ddHi]

  sol = solve_ivp(Hubble, t_span, y0, t_eval=acc, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, b))
  H = sol.y[0]
  return H

print(solHCC(acc, 70, 0.3, 2))

# fs8(t) para o modelo R2-AB:
def contrast_AB(t, y, O_m0, b):
  E_AB = y[0]
  dE_AB = y[1]
  ddE_AB = y[2]
  D_AB = y[3]
  dD_AB = y[4]

  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)

  e_AB = 12/np.log(1 + np.exp(2*b))
  M2 = e_AB/Delta
  R_AB = 6*E_AB*(2*E_AB + t*dE_AB)
  alpha = (R_AB/e_AB) - b

  if abs(alpha) < 25:
    s = 1/np.cosh(alpha)
  else:
    s = 0

  A = (3*O_m + 4*O_r)
  B = (2*t*E_AB*dE_AB*R_AB)/(3*M2)
  C = t*E_AB*dE_AB*(np.tanh(alpha) + 1)
  fAB1 = 6*(t**2)*(E_AB**2)/e_AB
  fAB2 = ddE_AB + ((dE_AB**2)/E_AB) + (5*dE_AB/t)
  if abs(alpha) < 15:
    F = ((fAB1*fAB2*s)**2)*np.tanh(alpha)
  else:
    F = 0
  if abs(alpha) < 15:
    I = 6*(t**3)*(E_AB**3)*((1/(3*M2)) + (0.5*s*s/e_AB))
  else:
    I = 6*(t**3)*(E_AB**3)*(1/(3*M2))

  U = (11*dE_AB**2/(t*E_AB)) + (dE_AB**3/(E_AB**2)) + (6*ddE_AB/t) + (4*dE_AB*ddE_AB/E_AB)
  dddE_AB = - ((A + B + C - F)/I) - U

  fR = 0.5*(1 + np.tanh(alpha)) + R_AB/(3*M2)
  fRR= (0.5/e_AB)*s**2 + 1/(3*M2)

  gaux3 = (fRR/fR)*((k/100)/t)**2
  Geffn = (1/fR)*(1 + 4*gaux3)/(1 + 3*gaux3)
  fABaux1 = 3*Geffn
  fABaux2 = 2*t*t*E_AB*E_AB

  ddD_AB = - ((3/t) + (dE_AB/E_AB))*dD_AB + (fABaux1/fABaux2)*O_m*D_AB
  return [dE_AB, ddE_AB, dddE_AB, dD_AB, ddD_AB]

def D_AB(O_m0, b):
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  Ei = np.sqrt(O_mi + O_ri + O_L)
  dEi = - (Ei/ti) - ((O_mi + 2*O_ri - 2*O_L)/(2*ti*Ei))
  au1 = Ei/(ti**2)
  au2 = 0.5*(Ei + ti*dEi)/(ti*Ei)
  au3 = (O_mi + 2*O_ri - 2*O_L)/(ti*Ei)
  au4 = (3*O_mi + 8*O_ri)/Ei
  ddEi = au1 + au2*au3 + 0.5*(ti**(-2))*au4 - (dEi/ti)
  y0 = [Ei, dEi, ddEi, 0.2, 1]

  sol_AB = solve_ivp(contrast_AB, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(O_m0, b))
  D_AB = sol_AB.y[3]
  return D_AB

def fs8_AB(arsd, O_m0, sig80, b):
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  Ei = np.sqrt(O_mi + O_ri + O_L)
  dEi = - (Ei/ti) - ((O_mi + 2*O_ri - 2*O_L)/(2*ti*Ei))
  au1 = Ei/(ti**2)
  au2 = 0.5*(Ei + ti*dEi)/(ti*Ei)
  au3 = (O_mi + 2*O_ri - 2*O_L)/(ti*Ei)
  au4 = (3*O_mi + 8*O_ri)/Ei
  ddEi = au1 + au2*au3 + 0.5*(ti**(-2))*au4 - (dEi/ti)
  y0 = [Ei, dEi, ddEi, 0.2, 1]

  sol_AB = solve_ivp(contrast_AB, t_span, y0, t_eval=arsd, method='LSODA', rtol = 10**(-6), args=(O_m0, b))
  dD_AB = sol_AB.y[4]
  fs8_AB = sig80*sol_AB.t*(dD_AB/D_AB(O_m0, b)[999])
  return fs8_AB

print(fs8_AB(arsd, 0.3, 0.8, 8))

# m_B(z) para o modelo R2-AB:
def Hubble(t, y, H0, O_m0, b):
  H  =  y[0]
  dH  = y[1]
  ddH = y[2]

  O_m = O_m0*t**(-3)
  O_r = O_r0*t**(-4)

  R_vac = 12*H0**2
  e_AB = R_vac/np.log(1 + np.exp(2*b))
  M2 = e_AB/Delta

  R = 6*H*(2*H + t*dH)
  alpha = (R/e_AB) - b
  if abs(alpha) < 15:
    s = 1/np.cosh(alpha)
  else:
    s = 0

  A = H0*H0*(3*O_m + 4*O_r)
  B = t*H*dH*(np.tanh(alpha) + 1)
  C = 4*t*H*H*dH*(t*dH + 2*H)/M2
  if abs(alpha) < 15:
    D = ((6*t*t*H*H)/e_AB)*(((5*dH/t) + (dH*dH/H) +ddH)**2)*np.tanh(alpha)*s*s
    E = 6*(t**3)*(H**3)*((1/(3*M2)) + (0.5*s*s/e_AB))
  else:
    D = 0
    E = 6*(t**3)*(H**3)/(3*M2)

  F = (11*dH*dH/(t*H)) + (dH*dH*dH/(H*H)) + (6*ddH/t) + (4*dH*ddH/H)

  dddH = - ((A + B + C - D)/E) - F
  return [dH, ddH, dddH]

def solution(H0, O_m0, b):
  t_span = [0.2, 1]
  ti = 0.2
  O_mi = O_m0*ti**(-3)
  O_ri = O_r0*ti**(-4)
  O_L = 1 - O_m0
  Hi = H0*np.sqrt(O_mi + O_ri + O_L)
  dHi = - ((H0*H0)/(2*ti*Hi))*(3*O_mi + 4*O_ri)
  ddHi = 0.5*(H0/(ti*Hi))**2*(Hi + ti*dHi)*(3*O_mi + 4*O_ri) + 0.5*(H0/(ti*Hi))**2*Hi*(9*O_mi + 16*O_ri)
  y0 = [Hi, dHi, ddHi]

  sol = solve_ivp(Hubble, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, b))
  H = sol.y[0]
  return H

# Condições iniciais = GR:
def Int_GR(H0, O_m0):
  ms = H0*np.sqrt(O_m0)
  O_L = 1 - O_m0
  hyper = sp.special.hyp2f1
  O_m = O_m0*t**(-3)
  H_GR = H0*np.sqrt(O_m + O_L)

  x1 = - 1/(6*w)
  x2 = 1 + x1
  x3 = 1 - (1/O_m0)
  x4 = 1 - ((1/O_m)*(H_GR/H0)**2)

  IntGR = (2/ms)*(hyper(1/2,x1,x2,x3) - np.sqrt(t)*hyper(1/2,x1,x2,x4))
  return IntGR

# Integral em MG:
def IntMG(H0, O_m0, b):
  y = 1/((t**2)*solution(H0, O_m0, b))
  IntMG = Int_GR(H0, O_m0)[0] + integrate.cumulative_trapezoid(y, t, initial=0)
  return IntMG

# Primitiva:
def Int_MG(H0, O_m0, b):
  Int_MG = IntMG(H0, O_m0, b)[999] - IntMG(H0, O_m0, b)
  return Int_MG

# Interpolação com os dados:
def IntMG_interp(H0, O_m0, b):
  x_interp = df['acmb']
  y_interp = np.interp(x_interp, t, Int_MG(H0, O_m0, b))
  return y_interp

# Distância-luminosidade:
def Lumi_MG(H0, O_m0, b):
  dL_MG = (299792.458/df['acmb'])*(IntMG_interp(H0, O_m0, b))
  return dL_MG

# Magnitude relativa:
def mag_MG(a_sn, H0, O_m0, Mb, b):
  mb_MG = 5*np.log10(Lumi_MG(H0, O_m0, b)) + 25 + Mb
  return mb_MG

print(mag_MG(a_sn, 72, 0.3, - 19.3, 2))

# --------------- chi2 CC --------------- #
def chiCC(acc, H0, O_m0, b, y_cc, yerr_cc):
    ycc_model = solHCC(acc, H0, O_m0, b)
    return np.sum( ((y_cc - ycc_model)/ yerr_cc) ** 2 )

def chi2cc(theta_cc, acc, y_cc, yerr_cc):
    H0, O_m0, b = theta_cc
    return chiCC(acc, H0, O_m0, b, y_cc, yerr_cc)

print(chiCC(acc, 72, 0.32, 2, y_cc, yerr_cc))
#-------------------------------------------------------------------------------

# --------------- chi2 RSD --------------- #
def chiRSD(arsd, O_m0, sig80, b, y_rsd, yerr_rsd):
    yrsd_model = fs8_AB(arsd, O_m0, sig80, b)
    return np.sum( ( (y_rsd - yrsd_model)/yerr_rsd ) ** 2 )

def chi2rsd(theta_rsd, arsd, y_rsd, yerr_rsd):
    O_m0, sig80, b = theta_rsd
    return chiRSD(arsd, O_m0, sig80, b, y_rsd, yerr_rsd)

print(chiRSD(arsd, 0.315, 0.811, 2, y_rsd, yerr_rsd))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe --------------- #
def delta(a_sn, H0, O_m0, Mb, b, y_sn):
  mb_model = mag_MG(a_sn, H0, O_m0, Mb, b)
  delta = y_sn - mb_model
  return delta

def chi2_SN(a_sn, H0, O_m0, Mb, b, y_sn, Icov):
  chisq = np.sum(np.dot(np.dot(delta(a_sn, H0, O_m0, Mb, b, y_sn), Icov), delta(a_sn, H0, O_m0, Mb, b, y_sn)))
  return chisq

def chisq_SN(theta_sn, a_sn, y_sn, Icov):
    H0, O_m0, Mb, b = theta_sn
    return chi2_SN(a_sn, H0, O_m0, Mb, b, y_sn, Icov)

print(chisq_SN([72, 0.32, -19.253, 2], a_sn, y_sn, Icov))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe+CC+RSD --------------- #

def chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, b, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    chicc = chiCC(acc, H0, O_m0, b, y_cc, yerr_cc)
    chirsd = chiRSD(arsd, O_m0, sig80, b, y_rsd, yerr_rsd)
    chisn = chi2_SN(a_sn, H0, O_m0, Mb, b, y_sn, Icov)
    return  chicc + chirsd + chisn

def chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, b = theta
    return chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, b, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(chi2_tot([70, 0.3, 0.8, -19.253, 2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))
#-------------------------------------------------------------------------------

# likelihood:
def lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, b = theta #theta (vetor) é o parâmetro que varia no fit. Cada componente dele vai variar no fit. É ele quem determina quem está variando
    return -0.5 * chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov) #a exponencial da likelihood é o chi2

print(lnlike([70, 0.3, 0.8, -19.253, 2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

def lnprior(theta):
    H0, O_m0, sig80, Mb, b = theta
    if 54 < H0 < 76 and 0.1 < O_m0 < 0.5 and 0.7 < sig80 < 0.9 and -20.2 < Mb < -19 and 1.6 < b < 12:
        return 0.0
    return -np.inf

def lnprob(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    lp = lnprior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(lnprob([70, 0.3, 0.8, -19.253, 2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

data = (acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)
nwalkers =  40   #The number of walkers in the ensemble.
niter = 10000 #número de interações
initial = np.array([70, 0.3, 0.8, -19.253, 5]) #chute inicial para os parâmetros livres
ndim = len(initial) #Number of dimensions in the parameter space.
p0 = [np.array(initial) + 1e-4 * np.random.randn(ndim) for i in range(nwalkers)]

# RUN MCMC:
with Pool() as pool:
    def main(p0,nwalkers,niter,ndim,lnprob,data):
        sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=data, pool=pool)

        print("Running burn-in...") #é a primeira fase do mcmc. É a fase que é jogada fora, porque é uma fase muito influenciada pelo chute inicial.
        p0, _, _ = sampler.run_mcmc(p0, 1500, progress=True) # 2000 é o número de interações.
        sampler.reset()

        print("Running production...") #depois que tira o burn-in, a cadeia esquece do passado.
        pos, prob, state = sampler.run_mcmc(p0, niter, progress=True)

        return sampler, pos, prob, state

    sampler, pos, prob, state = main(p0,nwalkers,niter,ndim,lnprob,data)

burnin = 1500
like_model =  sampler.get_log_prob(discard=burnin, flat=False)
chi2_model = -2*like_model

np.savetxt('log_pro_SNe+CC+RSD_AB.txt', like_model, fmt="%s")
print(chi2_model.min())

samples1 = sampler.flatchain
samples1[np.argmax(sampler.flatlnprobability)]
np.savetxt("Results_SNe+CC+RSD_AB.txt", samples1, fmt="%s")

labels = ['H0','O_m0', 'sig80', 'Mb', 'b']
fig = corner.corner(samples1,show_titles=True,labels=labels,plot_datapoints=True)
plt.savefig('MCMC_AB_fs8+CC_SNIa.pdf', dpi=520, format='pdf', bbox_inches='tight')



