# -*- coding: utf-8 -*-
"""MCMC_FQ3_Fulldata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsl5fL009RNwaKYgYZxwT9rD3elqjpBB
"""

# Libraries:
import numpy as np
import scipy as sp
import pandas as pd
import math
from scipy import integrate
from scipy.integrate import solve_ivp
from multiprocessing import Pool
import emcee
import time
from chainconsumer import ChainConsumer
import corner
import matplotlib.pyplot as plt

# Fiducial:
ti = 0.2
tf = 1.0
p = 1000
O_r0 = 0
w = -1
t_span = [ti, tf]
t = np.linspace(ti, tf, p)
z = (1/t) - 1

# Dados:

# --------------- Dados CC --------------- #
aCC = [0.3372681281618887, 0.36363636363636365, 0.39525691699604737,
          0.41152263374485604, 0.4231908590774439, 0.4347826086956522,
          0.4909180166912126, 0.5263157894736842, 0.5319148936170213,
          0.5333333333333333, 0.5614823133071308, 0.5952380952380952,
          0.6277463904582549, 0.6756756756756757, 0.6764526821348847,
          0.6802721088435374, 0.689797889218459, 0.7019021548396153,
          0.7140816909454443, 0.7142857142857143, 0.7245326764237068,
          0.7396449704142013, 0.78125, 0.7874015748031495, 0.8333333333333334,
          0.8340283569641367, 0.8481764206955046, 0.8547008547008548,
          0.8928571428571428, 0.9174311926605504, 0.9345794392523364]

HCC = [186.5, 202.0, 140.0, 177.0, 160.0, 168.0, 154.0, 117.0, 90.0, 125.0,
          105.0, 92.0, 104.0, 97.0, 80.9, 89.0, 92.8, 87.1, 77.0, 95.0, 83.0,
          83.0, 88.8, 77.0, 72.9, 75.0, 75.0, 83.0, 68.6, 69.0, 69.0]

sigmaCC = [50.4, 40.0, 14.0, 18.0, 33.6, 17.0, 20.0, 23.0, 40.0, 17.0,
              12.0, 8.0, 13.0, 62.0, 9.0, 49.6, 12.9, 11.2, 10.2, 17.0, 13.5,
              14.0, 36.6, 14.0, 29.6, 5.0, 4.0, 8.0, 26.2, 12.0, 19.6]

CC = pd.DataFrame({"aCC":aCC, "HCC":HCC, "sigmaCC":sigmaCC})

acc = CC['aCC']
zcc = 1/CC['aCC'] - 1
y_cc = CC['HCC']
yerr_cc = CC['sigmaCC']
#-------------------------------------------------------------------------------

# --------------- Dados RSD --------------- #
aRSD = [0.33967391, 0.339673911, 0.41666667, 0.44843049, 0.48780488, 0.50556117, 0.53763441, 0.57803468, 0.5790388, 0.58139535,
        0.6097561, 0.62111801, 0.625, 0.6251, 0.62893082, 0.63694268, 0.64102564, 0.65789474, 0.66225166, 0.67567568, 0.69444444,
        0.694444441, 0.71428571, 0.72463768,  0.73529412, 0.75757576, 0.76335878, 0.8, 0.84745763, 0.86956522, 0.90909091, 0.97087379,
        0.98039216, 0.980392161, 0.999001]

fRSD = [0.364, 0.342, 0.482, 0.385, 0.28, 0.379, 0.46, 0.437, 0.296, 0.454, 0.379, 0.436, 0.49, 0.39, 0.452, 0.501, 0.472, 0.483,
         0.458 , 0.458, 0.426, 0.413, 0.461, 0.497, 0.409, 0.427, 0.384, 0.3512, 0.36, 0.49, 0.37, 0.404, 0.428, 0.314, 0.505]

sigmaRSD = [0.106, 0.07, 0.116, 0.099, 0.08, 0.176, 0.09, 0.072, 0.0765, 0.139, 0.054, 0.034, 0.12, 0.063, 0.061,  0.051, 0.063, 0.075,
           0.038, 0.063, 0.062, 0.08, 0.086, 0.045, 0.098, 0.056, 0.083, 0.0583, 0.09, 0.145, 0.13, 0.0815, 0.0465, 0.048, 0.085]

RSD = pd.DataFrame({'aRSD':aRSD, 'fRSD':fRSD, 'sigmaRSD':sigmaRSD})

arsd = RSD['aRSD']
zrsd = 1/RSD['aRSD'] - 1
y_rsd = RSD['fRSD']
yerr_rsd = RSD['sigmaRSD']
#-------------------------------------------------------------------------------

# --------------- Dados SNe --------------- #
df= pd.read_csv('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES.dat', sep=' ')
#df= pd.read_csv('/content/Pantheon+SH0ES.dat', sep=' ')
df=df.sort_values("zCMB", ascending=False)
df['acmb'] = 1/(1+df["zCMB"])
a_sn = df['acmb']
y_sn = df["m_b_corr"]

mcov = np.loadtxt('/home/usuario/Downloads/DataRelease-main/Pantheon+_Data/4_DISTANCES_AND_COVAR/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
#mcov = np.loadtxt('/content/Pantheon+SH0ES_STAT+SYS.cov', skiprows=1)
cov = np.reshape(mcov, (1701, 1701))
Icov=np.linalg.inv(cov)
Icov
#-------------------------------------------------------------------------------

def Hubble_Q3(acc, H0, O_m0):
    O_m = O_m0*acc**(-3)
    O_L = 1 - O_m0 - O_r0
    H_Q3 = H0*np.sqrt(O_m + O_L)
    return H_Q3

#print(Hubble_Q3(acc, 70, 0.3))

# Modelo f(Q)3
def contrast_Q3(t, y, H0, O_m0, m):
    D_Q3 = y[0]
    dD_Q3 = y[1]

    O_m = O_m0*t**(-3)
    O_L = 1 - O_m0 - O_r0

    M = m*H0

    H_Q3 = H0*np.sqrt(O_m + O_L)
    dH_Q3 = -(3/2)*H0*(H0/H_Q3)*(O_m/t) # derivada de H com relação ao fator de escala

    Q = 6*(H_Q3)**2

    dfQ_3 = 1 + M*(Q**(-1/2)) / 2

    f1 = 3*(H0**2)*O_m
    f2 = 2*(t**2)*(H_Q3**2)*dfQ_3

    ddD_Q3 = - ((3/t) + (dH_Q3/H_Q3))*dD_Q3 + (f1/f2)*D_Q3  # equação do contraste
    return [dD_Q3, ddD_Q3]


def D_Q3(H0, O_m0, m):
    y0 = [ti, 1]
    sol_Q3 = solve_ivp(contrast_Q3, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
    D_Q3 = sol_Q3.y[0]
    return D_Q3

def fs8_Q3(arsd, H0, O_m0, sig80, m):
    y0 = [0.2, 1]
    sol_Q3 = solve_ivp(contrast_Q3, t_span, y0, t_eval=arsd, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, m))
    dD_Q3 = sol_Q3.y[1]
    fsig8_Q3 = sig80*sol_Q3.t*(dD_Q3/D_Q3(H0, O_m0, m)[999])
    return fsig8_Q3

#print(fs8_Q3(arsd, 70, 0.3, 0.8, 2))

# m_B(t) from GR/LCDM model:
def Int_GR(H0, O_m0):
  ms = H0*np.sqrt(O_m0)
  O_L = 1 - O_m0
  hyper = sp.special.hyp2f1
  O_m = O_m0*t**(-3)
  H_GR = H0*np.sqrt(O_m + O_L)

  x1 = - 1/(6*w)
  x2 = 1 + x1
  x3 = 1 - (1/O_m0)
  x4 = 1 - ((1/O_m)*(H_GR/H0)**2)

  IntGR = (2/ms)*(hyper(1/2,x1,x2,x3) - np.sqrt(t)*hyper(1/2,x1,x2,x4))
  return IntGR

def IntGR_interp(H0, O_m0):
  x_interp = df['acmb']
  y_interp = np.interp(x_interp, t, Int_GR(H0, O_m0))
  return y_interp

def Lumi_GR(H0, O_m0):
  dL_MG = (299792.458/df['acmb'])*(IntGR_interp(H0, O_m0))
  return dL_MG

def mag_GR(a_sn, H0, O_m0, Mb):
  mb_GR = 5*np.log10(Lumi_GR(H0, O_m0)) + 25 + Mb
  return mb_GR

#print(mag_GR(a_sn, 70, 0.3, - 19.3))

# --------------- chi2 CC --------------- #
def chiCC(acc, H0, O_m0, y_cc, yerr_cc):
    ycc_model = Hubble_Q3(acc, H0, O_m0)
    return np.sum( ((y_cc - ycc_model)/ yerr_cc) ** 2 )

def chi2cc(theta_cc, acc, y_cc, yerr_cc):
    H0, O_m0 = theta_cc
    return chiCC(acc, H0, O_m0, y_cc, yerr_cc)

#print(chiCC(acc, 70, 0.3, y_cc, yerr_cc))
#-------------------------------------------------------------------------------

# --------------- chi2 RSD --------------- #
def chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd):
    yrsd_model = fs8_Q3(arsd, H0, O_m0, sig80, m)
    return np.sum( ( (y_rsd - yrsd_model)/yerr_rsd ) ** 2 )

def chi2rsd(theta_rsd, arsd, y_rsd, yerr_rsd):
    H0, O_m0, sig80, m = theta_rsd
    return chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd)

#print(chiRSD(arsd, 70, 0.3, 0.8, 0.3, y_rsd, yerr_rsd))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe --------------- #
def delta(a_sn, H0, O_m0, Mb, y_sn):
  mb_model = mag_GR(a_sn, H0, O_m0, Mb)
  delta = y_sn - mb_model
  return delta

def chi2_SN(a_sn, H0, O_m0, Mb, y_sn, Icov):
  chisq = np.sum(np.dot(np.dot(delta(a_sn, H0, O_m0, Mb, y_sn), Icov), delta(a_sn, H0, O_m0, Mb, y_sn)))
  return chisq

def chisq_SN(theta_sn, a_sn, y_sn, Icov):
    H0, O_m0, Mb = theta_sn
    return chi2_SN(a_sn, H0, O_m0, Mb, y_sn, Icov)

#print(chisq_SN([70, 0.315, -19.253], a_sn, y_sn, Icov))
#-------------------------------------------------------------------------------

# --------------- chi2 SNe+CC+RSD --------------- #

def chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, m, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    chicc = chiCC(acc, H0, O_m0, y_cc, yerr_cc)
    chirsd = chiRSD(arsd, H0, O_m0, sig80, m, y_rsd, yerr_rsd)
    chisn = chi2_SN(a_sn, H0, O_m0, Mb, y_sn, Icov)
    return  chicc + chirsd + chisn

def chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, m = theta
    return chi_tot(acc, arsd, a_sn, H0, O_m0, sig80, Mb, m, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

print(chi2_tot([70, 0.3, 0.8, -19.253, 2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))
#-------------------------------------------------------------------------------

# likelihood:
def lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    H0, O_m0, sig80, Mb, m = theta
    return -0.5 * chi2_tot(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

#print(lnlike([70, 0.3, 0.8, -19.253, -0.2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

def lnprior(theta):
    H0, O_m0, sig80, Mb, m = theta
    if 54 < H0 < 76 and 0.1 < O_m0 < 0.5 and 0.6 < sig80 < 0.9 and -20.2 < Mb < -19 and -3 < m < 3:
        return 0.0
    return -np.inf

def lnprob(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov):
    lp = lnprior(theta)
    if not np.isfinite(lp):
        return -np.inf
    return lp + lnlike(theta, acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)

#print(lnprob([70, 0.3, 0.8, -19.253, 2], acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov))

data = (acc, arsd, a_sn, y_cc, y_rsd, y_sn, yerr_cc, yerr_rsd, Icov)
nwalkers =  40   #The number of walkers in the ensemble.
niter = 10000 #número de interações
initial = np.array([70, 0.3, 0.8, -19.253, 1]) #chute inicial para os parâmetros livres
ndim = len(initial) #Number of dimensions in the parameter space.
p0 = [np.array(initial) + 1e-4 * np.random.randn(ndim) for i in range(nwalkers)]

# RUN MCMC:
with Pool() as pool:
    def main(p0,nwalkers,niter,ndim,lnprob,data):
        sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=data, pool=pool)

        print("Running burn-in...")
        p0, _, _ = sampler.run_mcmc(p0, 1500, progress=True)
        sampler.reset()

        print("Running production...")
        pos, prob, state = sampler.run_mcmc(p0, niter, progress=True)

        return sampler, pos, prob, state

    sampler, pos, prob, state = main(p0,nwalkers,niter,ndim,lnprob,data)

burnin = 1500
like_model =  sampler.get_log_prob(discard=burnin, flat=False)
chi2_model = -2*like_model

#np.savetxt('log_pro_FQ3_Fulldata.txt', like_model, fmt="%s")
print(chi2_model.min())

samples1 = sampler.flatchain
samples1[np.argmax(sampler.flatlnprobability)]
#np.savetxt("Resultados_FQ3_Fulldata.txt", samples1, fmt="%s")

labels = ['H0','O_m0', 'sig80', 'Mb', 'm']
fig = corner.corner(samples1,show_titles=True,labels=labels,plot_datapoints=True)
