# -*- coding: utf-8 -*-
"""Teoria F2(Q) - Contraste, f(z) e fs8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlpROK0EHUKjwn44H9x430xF94MsW2Gm
"""

# Bibliotecas:
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True

# Parâmetros:
H0 = 67.4
O_m0 = 0.315
O_r0 = 0

ti = 0.17
t = np.linspace(ti, 1, 1000)
z = (1/t) - 1

H_RG = H0*np.sqrt(O_m0*t**(-3) + 1 - O_m0 )

# Modelo f(Q) - 2
def Densidade_Q2(t, y, H0, O_m0, m):
    D_Q2 = y[0]
    dD_Q2 = y[1]

    O_m = O_m0*t**(-3)

    M = m*H0
    M4 = M**4

    H_Q2 = np.sqrt( (H0**2)*O_m / 2 + (1/6)*np.sqrt(9*H0**4*O_m**2 + M4) ) # eq de Friedmann minha
    dH_Q2 = ( (M**4 - 36*H_Q2**4)*H_Q2 ) / (2*t*(M**4 + 12*H_Q2**4) ) # obtida com a 1 eq de Friedmann minha

    Q = 6*(H_Q2**2)

    dfQ_2 = 1 - (M**4/Q**2)  # primeira derivada da f(Q)

    f1 = 3*(H0**2)*O_m
    f2 = 2*(t**2)*(H_Q2**2)*dfQ_2

    ddD_Q2 = - ((3/t) + dH_Q2/H_Q2)*dD_Q2 + ( (f1/f2)*D_Q2 )  # equação do contraste
    return [dD_Q2, ddD_Q2]

def solD_fQ2(H0, O_m0, m):
    # Espaço de integração:
    t_span = [ti, 1]
    t = np.linspace(ti, 1, 1000)

    # Condições iniciais:
    y0 = [ti, 1]

    # Solução:
    sol_Q2 = solve_ivp(Densidade_Q2, t_span, y0, t_eval=t, method='LSODA', args=(H0, O_m0, m))
    D_Q2 = sol_Q2.y[0]
    return D_Q2

plt.plot(z, solD_fQ2(70, 0.3, 2.0331), color='slategray', label='$F_2(Q)$', linewidth = 2)
plt.legend()
plt.xlabel('$z$')
plt.ylabel('$\delta(z)$')
#plt.savefig('delta(z)_fQ2.pdf', dpi=520, format='pdf', bbox_inches='tight')
plt.show()

# Solução para f(z)
def solf_fQ2(H0, O_m0, m):
    t_span = [ti, 1]
    y0 = [ti, 1]
    sol = solve_ivp(Densidade_Q2, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, m))
    D_Q2 = sol.y[0]
    dD_Q2 = sol.y[1]
    f_Q2 = sol.t*(dD_Q2/D_Q2)
    return f_Q2

plt.plot(z, solf_fQ2(70, 0.3, 2.0331), color='slategray', label='$F_2(Q)$', linewidth = 2)
plt.legend()
plt.xlabel('$z$')
plt.ylabel('$f(z)$')
#plt.savefig('f_fQ2.png', dpi=520, format='png', bbox_inches='tight')
plt.show()

def solfs8_fQ2(H0, O_m0, sig8, m):
    y0 = [ti, 1]
    t_span = [ti, 1]
    sol = solve_ivp(Densidade_Q2, t_span, y0, t_eval=t, method='LSODA', rtol = 10**(-6), args=(H0, O_m0, m))
    D = sol.y[0]
    dD = sol.y[1]
    fs8 = sig8*sol.t*(dD/solD_fQ2(H0, O_m0, m)[999])
    return fs8

plt.plot(z, solfs8_fQ2(70, 0.3, 0.8, 2.0331), color='slategray', label='$F_2(Q)$', linewidth = 2)

plt.legend()
plt.xlabel('$z$')
plt.ylabel('$[f\sigma_8](z)$')
#plt.savefig('fs8(z)_fQ2.pdf', dpi=520, format='pdf', bbox_inches='tight')
plt.show()