# -*- coding: utf-8 -*-
"""triangle_plot_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OZgFrfbZCiS-EJL0I6bfBesF_Yg-jve
"""

import numpy as np
import corner
import matplotlib.pyplot as plt

# Substitua 'seu_arquivo.txt' pelo caminho do arquivo
# Ajuste 'delimiter' conforme o formato do arquivo (espaço, vírgula, etc.)
data = np.loadtxt('/home/usuario/Documentos/Códigos/Estudo_do_contraste/MCMC/log_pro_SNe+CC+RSD_Starob_n2_new.txt', delimiter=',')

# Exclua a coluna do log da probabilidade (supondo que esteja na última coluna)
# Se os parâmetros estão nas colunas [0, 1, ..., N-1] e a probabilidade na coluna N:
params = data[:, :-1]  # Exclui a última coluna

# Configuração do corner plot
figure = corner.corner(
    params,
    labels=["Param 1", "Param 2", "Param 3"],  # Substitua pelos nomes dos parâmetros
    truths=[None, None, None],  # Valores verdadeiros, se aplicável
    quantiles=[0.16, 0.5, 0.84],
    show_titles=True,
    title_kwargs={"fontsize": 12},
)

# Salvar ou exibir o plot
plt.savefig("triangle_plot_test.png")
plt.show()