# -*- coding: utf-8 -*-
"""Untitled115.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I82mkvZPS95yILaRX6n8ztDR8FS4skma
"""

import numpy as np
import matplotlib.pyplot as plt
import corner
from chainconsumer import ChainConsumer

# Parâmetros para facilitar a leitura
#caminho_arquivo = '/content/Results_teste_Starob_n2.txt'
caminho_arquivo = '/home/usuario/Documentos/Códigos/Estudo_do_contraste/MCMC/Results_teste_Starob_n2.txt'
nomes_dos_parametros = [r"$H_0$", r"$\Omega_{m,0}$", r"$\sigma_{8,0}$", r"$M_B$", r"$\lambda^{-1}$"]

# Carrega os dados do arquivo .txt
dados = np.genfromtxt(caminho_arquivo, delimiter=',')

# Gera o triangle plot
fig = corner.corner(
    dados,
    labels=nomes_dos_parametros,
    show_titles=True,
    title_kwargs={"fontsize": 12},
    quantiles=[0.16, 0.5, 0.84],
    plot_contours=True,
    contourf_kwargs={"alpha": 0.7}
)

# Exibe o plot
plt.show()


# Gera o triangle plot usando ChainConsumer
c = ChainConsumer()
c.add_chain(dados, parameters=nomes_dos_parametros)
c.configure(shade_alpha=1, summary=True, colors=["blue"], max_ticks=4,legend_artists=True)
fig_chainconsumer = c.plotter.plot()
fig_chainconsumer.set_size_inches(3 + fig_chainconsumer.get_size_inches())
plt.savefig("MCMC_S_n2_new.pdf", dpi=520, format='pdf', bbox_inches='tight')
plt.show()



